---
- name: Deploy the staging version
  hosts: localhost
  become: true
  vars:
    server_environment: production
    server_image_version: release-0.0.2
    server_host_port: 8081
    server_container_port: 5000
  roles:
    - server
